version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: recipes_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  app:
    image: StoreAndShareYourRecipes
    container_name: recipes_app
    depends_on:
      - mysql
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - server/.env
